export const CLUB_ALL_REQUEST = "CLUB_ALL_REQUEST";
export const CLUB_ALL_SUCCESS = "CLUB_ALL_SUCCESS";
export const CLUB_ALL_FAIL = "CLUB_ALL_FAIL";

export const CLUB_SINGLE_REQUEST = "CLUB_SINGLE_REQUEST";
export const CLUB_SINGLE_SUCCESS = "CLUB_SINGLE_SUCCESS";
export const CLUB_SINGLE_FAIL = "CLUB_SINGLE_FAIL";

export const CLUB_CREATE_REQUEST = "CLUB_CREATE_REQUEST";
export const CLUB_CREATE_SUCCESS = "CLUB_CREATE_SUCCESS";
export const CLUB_CREATE_FAIL = "CLUB_CREATE_FAIL";
export const CLUB_CREATE_RESET = "CLUB_CREATE_RESET";

export const CLUB_SET_ROLE_REQUEST = "CLUB_SET_ROLE_REQUEST";
export const CLUB_SET_ROLE_SUCCESS = "CLUB_SET_ROLE_SUCCESS";
export const CLUB_SET_ROLE_FAIL = "CLUB_SET_ROLE_FAIL";
export const CLUB_SET_ROLE_RESET = "CLUB_SET_ROLE_RESET";

export const CLUB_DELETE_REQUEST = "CLUB_DELETE_REQUEST";
export const CLUB_DELETE_SUCCESS = "CLUB_DELETE_SUCCESS";
export const CLUB_DELETE_FAIL = "CLUB_DELETE_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";