export const SUBTASK_ALL_REQUEST = "SUBTASK_ALL_REQUEST";
export const SUBTASK_ALL_SUCCESS = "SUBTASK_ALL_SUCCESS";
export const SUBTASK_ALL_FAIL = "SUBTASK_ALL_FAIL";
export const SUBTASK_ALL_RESET = "SUBTASK_ALL_RESET";

export const SUBTASK_SINGLE_REQUEST = "SUBTASK_SINGLE_REQUEST";
export const SUBTASK_SINGLE_SUCCESS = "SUBTASK_SINGLE_SUCCESS";
export const SUBTASK_SINGLE_FAIL = "SUBTASK_SINGLE_FAIL";
export const SUBTASK_SINGLE_RESET = "SUBTASK_SINGLE_RESET";

export const SUBTASK_CREATE_REQUEST = "SUBTASK_CREATE_REQUEST";
export const SUBTASK_CREATE_SUCCESS = "SUBTASK_CREATE_SUCCESS";
export const SUBTASK_CREATE_FAIL = "SUBTASK_CREATE_FAIL";
export const SUBTASK_CREATE_RESET = "SUBTASK_CREATE_RESET";

export const SUBTASK_UPDATE_REQUEST = "SUBTASK_UPDATE_REQUEST";
export const SUBTASK_UPDATE_SUCCESS = "SUBTASK_UPDATE_SUCCESS";
export const SUBTASK_UPDATE_FAIL = "SUBTASK_UPDATE_FAIL";
export const SUBTASK_UPDATE_RESET = "SUBTASK_UPDATE_RESET";

export const SUBTASK_DELETE_REQUEST = "SUBTASK_DELETE_REQUEST";
export const SUBTASK_DELETE_SUCCESS = "SUBTASK_DELETE_SUCCESS";
export const SUBTASK_DELETE_FAIL = "SUBTASK_DELETE_FAIL";
export const SUBTASK_DELETE_RESET = "SUBTASK_DELETE_RESET";

export const CLEAR_ERRORS = "CLEAR_ERRORS";