export const TASK_ALL_REQUEST = "TASK_ALL_REQUEST";
export const TASK_ALL_SUCCESS = "TASK_ALL_SUCCESS";
export const TASK_ALL_FAIL = "TASK_ALL_FAIL";

export const TASK_SINGLE_REQUEST = "TASK_SINGLE_REQUEST";
export const TASK_SINGLE_SUCCESS = "TASK_SINGLE_SUCCESS";
export const TASK_SINGLE_FAIL = "TASK_SINGLE_FAIL";

export const TASK_CREATE_REQUEST = "TASK_CREATE_REQUEST";
export const TASK_CREATE_SUCCESS = "TASK_CREATE_SUCCESS";
export const TASK_CREATE_FAIL = "TASK_CREATE_FAIL";
export const TASK_CREATE_RESET = "TASK_CREATE_RESET";

export const TASK_UPDATE_REQUEST = "TASK_UPDATE_REQUEST";
export const TASK_UPDATE_SUCCESS = "TASK_UPDATE_SUCCESS";
export const TASK_UPDATE_FAIL = "TASK_UPDATE_FAIL";

export const TASK_DELETE_REQUEST = "TASK_DELETE_REQUEST";
export const TASK_DELETE_SUCCESS = "TASK_DELETE_SUCCESS";
export const TASK_DELETE_FAIL = "TASK_DELETE_FAIL";
export const TASK_DELETE_RESET = "TASK_DELETE_RESET";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
