export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGIN_SUCESS = "LOGIN_SUCESS";
export const LOGIN_RESET = "LOGIN_RESET";

export const REGISTER_USER_REQUEST = "REGISTER_USER_REQUEST";
export const REGISTER_USER_FAIL = "REGISTER_USER_FAIL";
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
export const REGISTER_USER_RESET = "REGISTER_USER_RESET";

export const LOAD_USER_REQUEST = "LOAD_USER_REQUEST";
export const LOAD_USER_FAIL = "LOAD_USER_FAIL";
export const LOAD_USER_SUCESS = "LOAD_USER_SUCESS";

export const UPDATE_USERS_REQUEST = "UPDATE_USERS_REQUEST";
export const UPDATE_USERS_FAIL = "UPDATE_USERS_FAIL";
export const UPDATE_USERS_SUCESS = "UPDATE_USERS_SUCESS";
export const UPDATE_USERS_RESET = "UPDATE_USERS_RESET";

export const UPDATE_PASSWORD_REQUEST = "UPDATE_PASSWORD_REQUEST";
export const UPDATE_PASSWORD_FAIL = "UPDATE_PASSWORD_FAIL";
export const UPDATE_PASSWORD_SUCESS = "UPDATE_PASSWORD_SUCESS";
export const UPDATE_PASSWORD_RESET = "UPDATE_PASSWORD_RESET";

export const FORGOT_PASSWORD_REQUEST = "FORGOT_PASSWORD_REQUEST";
export const FORGOT_PASSWORD_FAIL = "FORGOT_PASSWORD_FAIL";
export const FORGOT_PASSWORD_SUCESS = "FORGOT_PASSWORD_SUCESS";
export const FORGOT_PASSWORD_RESET = "FORGOT_PASSWORD_RESET";

export const RESET_PASSWORD_REQUEST = "RESET_PASSWORD_REQUEST";
export const RESET_PASSWORD_FAIL = "RESET_PASSWORD_FAIL";
export const RESET_PASSWORD_SUCESS = "RESET_PASSWORD_SUCESS";

export const ALL_USERS_REQUEST = "ALL_USERS_REQUEST";
export const ALL_USERS_FAIL = "ALL_USERS_FAIL";
export const ALL_USERS_SUCESS = "ALL_USERS_SUCESS";

export const UPDATE_USER_REQUEST = "UPDATE_USER_REQUEST";
export const UPDATE_USER_FAIL = "UPDATE_USER_FAIL";
export const UPDATE_USER_SUCESS = "UPDATE_USER_SUCESS";
export const UPDATE_USER_RESET = "UPDATE_USER_RESET";

export const DELETE_USER_REQUEST = "DELETE_USER_REQUEST";
export const DELETE_USER_FAIL = "DELETE_USER_FAIL";
export const DELETE_USER_SUCESS = "DELETE_USER_SUCESS";
export const DELETE_USER_RESET = "DELETE_USER_RESET";

export const USER_DETAILS_REQUEST = "USER_DETAILS_REQUEST";
export const USER_DETAILS_FAIL = "USER_DETAILS_FAIL";
export const USER_DETAILS_SUCESS = "USER_DETAILS_SUCESS";

export const USER_ALL_REQUEST = "USER_ALL_REQUEST";
export const USER_ALL_FAIL = "USER_ALL_FAIL";
export const USER_ALL_SUCESS = "USER_ALL_SUCESS";

export const LOGOUT_SUCESS = "LOGOUT_SUCESS";
export const LOGOUT_FAIL = "LOGOUT_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";